name: trim_zero
description: Remove trailing 0 for Dart number string, gives you a pretty number or price.
version: 1.0.0
repository: https://github.com/sinkcup/dart-trim-zero

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  lints: '>=2.0.0'
  test: ^1.24.0
