name: pretty_number
description: Remove trailing 0 for Dart number string.
version: 0.1.0
repository: https://github.com/sinkcup/dart-pretty-number

environment:
  sdk: '>=2.12.0'

dev_dependencies:
  lints: '>=2.0.0'
  test: ^1.24.0
